export const DATA_SOURCE_TOKEN = Symbol("DATA_SOURCE_TOKEN");
export const TEST_AGENT_TOKEN = Symbol("TEST_AGENT_TOKEN");
export const CUSTOMER_REPOSITORY_TOKEN = Symbol("CUSTOMER_REPOSITORY_TOKEN");
export const PRODUCT_REPOSITORY_TOKEN = Symbol("PRODUCT_REPOSITORY_TOKEN");
export const ORDER_REPOSITORY_TOKEN = Symbol("ORDER_REPOSITORY_TOKEN");
